name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: sudo apt install -yq --no-install-recommends gfortran
      - name: Configure
        run: cmake .
      - name: Build
        run: make -j 4
      - name: Installation
        run: sudo make install
